spring:
  application:
    name: room-status
  cache:
    cache-names:
      - buildings
      - rooms
      - room-details
      - room-schedules

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html